version: '2'
services:
  db:
    image: postgres:11.2
    container_name: tend_postgres
    restart: always
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qazwsx123
      - POSTGRES_USER=postgres
  web:
    image: cyokin/tend:0.0.18
    build: tend
    container_name: tend_web
    restart: always
    environment:
      - tend.postgreSQL.host=db
      - tend.postgreSQL.port=5432
    ports:
      - "80:8080"
    volumes:
      - ./static:/opt/static
      - ./logs:/logs
    links:
      - db
  admin:
    image: cyokin/tend-admin:0.0.4
    build: tend-admin
    container_name: tend_admin
    restart: always
    environment:
      - tend.postgreSQL.host=db
      - tend.postgreSQL.port=5432
      - tend.postgreSQL.user=db
      - tend.postgreSQL.password=5432
    ports:
      - "8080:8080"
    volumes:
      - ./static:/opt/static
      - ./logs:/logs
    links:
      - db
  exporter:
    image: cyokin/tend-exporter:0.0.2
    build: tend-exporter
    container_name: tend_exporter
    restart: always
    environment:
      - tend.postgreSQL.host=db
      - tend.postgreSQL.port=5432
      - tend.postgreSQL.user=db
      - tend.postgreSQL.password=5432
      - spring.profiles.active=env
    volumes:
      - ./static:/opt/static
volumes:
  postgres:
