version: '2'
services:
  db:
    image: postgres:11.2
    container_name: tend_postgres
    restart: always
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qazwsx123
      - POSTGRES_USER=postgres
    networks:
      - tend_network
  web:
    image: cyokin/tend:1.0.1
    container_name: tend_web
    restart: always
    environment:
      - tend.postgreSQL.host=db
      - tend.postgreSQL.port=5432
    ports:
      - "80:8080"
    volumes:
      - ./static:/opt/static
      - ./logs:/logs
    depends_on:
      - db
    networks:
      - tend_network
volumes:
  postgres:
networks:
  tend_network:
